stages:
  - test
  - staging

testing:
  stage: test
  script:
    - echo "Testing"

staging:
  variables:
<<<<<<< .gitlab-ci.yml
    REACT_APP_API_URL: http://146.169.43.35:5000/
=======
    REACT_APP_API_URL: http://146.169.43.35:5000
>>>>>>> .gitlab-ci.yml
    ENV: staging
  stage: staging
  script:
    - source ~/.bashrc
    - npm install
    - CI=false npm run build
    - sudo rm -rf /usr/share/nginx/html/*
    - sudo cp -a build/. /usr/share/nginx/html/
    - sudo service nginx restart
  environment:
    name: staging
    url: http://146.169.43.35:3000/
  only:
    - master
